server:
  port: 8081
spring:
  application:
   name: spring-reactor-academy
  data:
    mongodb:
      uri: mongodb://localhost:27017/academia
jjwt:
  secret: f781e5651bf3e9b0163e266e3e381b028aa30da585dabddbff4c80d689d09609486fe5114c1bf06c5f0760c125d5fe0ea37fc1cb8cf31b6a68ec304f5e5a1fb0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
